version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: aben_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aben_data
      MYSQL_USER: aben_user
      MYSQL_PASSWORD: aben_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
